# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-24 13:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_key', models.TextField(default='', max_length=32, unique=True)),
                ('name', models.TextField(default='2016-11-24 13:59:27', max_length=200)),
                ('head', models.TextField(default='')),
                ('sample', models.TextField()),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'datatables',
            },
        ),
        migrations.CreateModel(
            name='DataTableItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('datatable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gathering.DataTable')),
            ],
        ),
        migrations.CreateModel(
            name='DataTableOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face', models.ImageField(blank=True, upload_to='profile_images')),
                ('website', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='datatable',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gathering.DataTableOwner'),
        ),
    ]
