# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-30 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gathering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='name',
            field=models.TextField(default='2016-11-30 07:38:47', max_length=200),
        ),
    ]
