# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-24 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gathering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatableitem',
            name='order_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='name',
            field=models.TextField(default='2016-11-24 14:00:13', max_length=200),
        ),
    ]
