# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-22 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gathering', '0002_datatable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='name',
            field=models.TextField(max_length=200),
        ),
    ]
