# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-22 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gathering', '0003_auto_20161122_0459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datatable',
            options={'verbose_name_plural': 'datatables'},
        ),
    ]
