# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-22 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gathering', '0004_auto_20161122_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='major_id',
            field=models.TextField(max_length=4),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='minor_id',
            field=models.TextField(max_length=4),
        ),
    ]
