# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-22 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gathering', '0006_auto_20161122_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datatable',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
