# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-22 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gathering', '0007_auto_20161122_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatable',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
